# Generated by Django 3.0.3 on 2020-08-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
